### PR TITLE
Create server.conf

### PR DESCRIPTION
**Pull request by JoeyJoeSco**
allow config replication in SH Cluster environment

### CODE REVIEW

**Comment by JoeyJoeSco** [comment]
We have seen issues with the Add-On removing configs in a clustered Search Head environment.  This will hopefully fix the issue by replicating the configs across the clustered search heads.

**Comment by eyalpalo** [comment]
@JoeyJoeSco  Hi, thank you for your contribution. This PR will be reviewed shortly.

**Comment by eyalpalo** [comment]
@JoeyJoeSco Hi, I would like us to have a short conversation about this change. When will you be available?

**Comment by JoeyJoeSco** [comment]
Anytime today works for me

**Comment by eyalpalo** [comment]
@JoeyJoeSco Next Tuesday? Can you send me your mail so I can schedule?

**Comment by JoeyJoeSco** [comment]
@eyalpalo JoeScordo27@gmail.com

**Comment by eyalpalo** [comment]
@JoeyJoeSco Closing this PR as the requested changes will be part of https://github.com/demisto/splunk-app/pull/46

Thank you again

**Pull request closed without merging**
